import type { Locale } from "../i18n/locale";
const en = {
  noCapabilities: "Manufacturing capabilities have not been provided.",
  noFilterValues: "No published parameters yet",
  clearAll: "Clear all",
  requestPricing: "Request pricing",
  share: "Share product",
  favorite: "Save product",
  quantity: "Quantity",
  sendInquiry: "Send inquiry",
  contactHint: "For product inquiries, samples or quotations",
  contact: "Contact supplier",
  capabilities: "Manufacturing capabilities",
  mainProducts: "Main products",
  sizeRange: "Size range",
  connection: "Connection type",
  material: "Material",
  quoteHint: "Quickly create a professional quote",
  quoteTool: "Quotation builder",
  costHint: "Estimate processing and material cost",
  costTool: "Cost calculator",
  weightHint: "Calculate part weight by size",
  weightTool: "Weight calculator",
  comingSoon: "Coming soon",
  signIn: "Sign in",
  portal: "Supplier portal",
  usefulTools: "Useful tools",
  tools: "Tools",
  products: "Products",
  suppliers: "Suppliers",
  join: "Join as supplier",
  home: "Home",
  language: "Language",
  menu: "Menu",
  heroTitle: "Find reliable manufacturing products and suppliers",
  heroDescription:
    "Explore industrial products, discover manufacturing expertise and find your next partner.",
  heroImage:
    "Industrial bearings, gears, electric motor, valve and precision components",
  search: "Search",
  searchPlaceholder: "Products, categories or keywords…",
  supplierPlaceholder: "Search company names…",
  industries: "Browse by industry",
  featured: "Featured products",
  viewAll: "View all",
  viewDetails: "View details",
  supplierProfile: "View supplier homepage",
  all: "All",
  filters: "Filters",
  categories: "Product categories",
  industry: "Industry",
  sort: "Sort by",
  newest: "Recently updated",
  name: "Name",
  clear: "Clear filters",
  noResults: "No results found",
  noResultsHint: "Try a different keyword or remove some filters.",
  empty: "No products published yet",
  loading: "Loading…",
  error: "Unable to load this content",
  retry: "Try again",
  notFound: "This page is unavailable",
  notFoundHint: "The product or supplier may have been removed.",
  previous: "Previous",
  next: "Next",
  page: "Page",
  results: "results",
  specifications: "Specifications",
  description: "Description",
  variant: "Variant",
  price: "Reference price",
  moq: "Minimum order",
  unit: "Unit",
  brand: "Brand",
  notProvided: "Not provided",
  noPhoto: "No image available",
  overview: "Overview",
  companyProfile: "Company profile",
  companyProducts: "Products from this supplier",
  location: "Location",
  address: "Registered address",
  founded: "Founded",
  albums: "Company gallery",
  profileNote:
    "Company and product information is supplied by the enterprise. Interface language changes do not translate submitted content.",
  contactNote:
    "Online inquiries are not available yet. You can browse product details and supplier profiles.",
  onboardTitle: "Bring your manufacturing expertise to new markets",
  onboardDescription:
    "Create a company presence and showcase your products. Submit your enterprise application to get started.",
  browse: "Browse products",
  footer: "Industrial products · Manufacturing expertise · New partnerships",
  footerAbout: "Discover industrial products, explore manufacturing capabilities and connect with your next business partner.",
  footerExplore: "Explore",
  footerEnterprise: "For enterprises",
  footerJoinHint: "Present your company and products. Start with an enterprise application.",
  footerRights: "All rights reserved.",
  noCompany: "No suppliers found",
  companyName: "Company name",
  category: "Category",
  productImage: "Product image",
  chooseImage: "View image",
  close: "Close",
};
const zh: typeof en = {
  noCapabilities: "企业暂未提供制造能力资料。",
  noFilterValues: "暂无已发布参数",
  clearAll: "清除全部",
  requestPricing: "咨询价格",
  share: "分享产品",
  favorite: "收藏产品",
  quantity: "数量",
  sendInquiry: "发送询盘",
  contactHint: "咨询产品、样品与报价",
  contact: "联系企业",
  capabilities: "制造能力",
  mainProducts: "主营产品",
  sizeRange: "尺寸规格",
  connection: "连接方式",
  material: "材质",
  quoteHint: "快速制作专业报价单",
  quoteTool: "报价单生成器",
  costHint: "估算加工与材料成本",
  costTool: "成本计算器",
  weightHint: "根据尺寸计算零件重量",
  weightTool: "重量计算器",
  comingSoon: "即将开放",
  signIn: "登录",
  portal: "企业平台",
  usefulTools: "实用工具",
  tools: "工具",
  products: "产品",
  suppliers: "企业",
  join: "企业入驻",
  home: "首页",
  language: "语言",
  menu: "菜单",
  heroTitle: "发现优质工业产品，连接专业制造企业",
  heroDescription: "浏览工业产品，了解制造能力，寻找下一位合作伙伴。",
  heroImage: "轴承、齿轮、电机、阀门与精密工业零件",
  search: "搜索",
  searchPlaceholder: "搜索产品、分类或关键词…",
  supplierPlaceholder: "搜索企业名称…",
  industries: "按行业浏览",
  featured: "精选产品",
  viewAll: "查看全部",
  viewDetails: "查看详情",
  supplierProfile: "查看企业主页",
  all: "全部",
  filters: "筛选",
  categories: "产品分类",
  industry: "行业",
  sort: "排序",
  newest: "最近更新",
  name: "名称",
  clear: "清除筛选",
  noResults: "暂无搜索结果",
  noResultsHint: "试试其他关键词，或减少筛选条件。",
  empty: "暂无已发布产品",
  loading: "正在加载…",
  error: "内容加载失败",
  retry: "重新加载",
  notFound: "页面暂不可用",
  notFoundHint: "该产品或企业可能已下架。",
  previous: "上一页",
  next: "下一页",
  page: "页",
  results: "条结果",
  specifications: "产品参数",
  description: "产品简介",
  variant: "规格",
  price: "参考价格",
  moq: "起订量",
  unit: "单位",
  brand: "品牌",
  notProvided: "暂未提供",
  noPhoto: "暂无图片",
  overview: "概览",
  companyProfile: "企业资料",
  companyProducts: "企业产品",
  location: "所在地",
  address: "注册地址",
  founded: "成立年份",
  albums: "企业相册",
  profileNote:
    "企业与产品资料由企业提供。切换界面语言不会自动翻译企业填写的内容。",
  contactNote: "在线询盘暂未开放，可先查看产品详情和企业资料。",
  onboardTitle: "让您的制造能力被更多客户看见",
  onboardDescription:
    "展示企业资料与产品，连接新的合作机会。从提交企业入驻申请开始。",
  browse: "浏览产品",
  footer: "工业产品 · 制造能力 · 合作机会",
  footerAbout: "发现工业产品，了解企业制造能力，寻找新的合作伙伴。",
  footerExplore: "发现与浏览",
  footerEnterprise: "企业服务",
  footerJoinHint: "展示企业资料与产品，从提交企业入驻申请开始。",
  footerRights: "保留所有权利。",
  noCompany: "暂无符合条件的企业",
  companyName: "企业名称",
  category: "分类",
  productImage: "产品图片",
  chooseImage: "查看图片",
  close: "关闭",
};
export function catalogCopy(locale: Locale) {
  return locale === "en" ? en : zh;
}
